-- Roster of "who is entered in this championship, driving for which team" —
-- deliberately separate from driver_classifications, which answers "how many
-- points / what position" and only gets a row once f1api.dev exposes a
-- drivers-championship entry. That can lag the announced grid, and never
-- arrives at all for a reserve driver who doesn't score. season_entries is fed
-- straight from GET /{year}/drivers, which already carries a teamId per
-- driver, so it's available as soon as f1api.dev itself knows the lineup.
--
-- One row per (championship, driver). Mid-season driver swaps are not
-- versioned here on purpose — see lib/sync/seasonRefresh.js.
CREATE TABLE season_entries (
  season_entry_id serial PRIMARY KEY,
  championship_id text REFERENCES championships(championship_id),
  driver_id text REFERENCES drivers(driver_id),
  team_id text REFERENCES teams(team_id),
  -- The one timestamptz column in this schema: every other date/time field
  -- mirrors a raw upstream string verbatim (hence `text`), but this one is
  -- generated by our own job, not parsed from an API response, so there's no
  -- round-trip-fidelity reason to store it as text. It also doubles as cheap
  -- cron observability: MAX(last_seen_at) answers "did the refresh job
  -- actually run" for a table that, unlike the others, is rewritten every run.
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (championship_id, driver_id)
);

CREATE INDEX idx_season_entries_driver ON season_entries(driver_id);
CREATE INDEX idx_season_entries_team ON season_entries(team_id);

-- Seed from what we already infer today, so the table is immediately useful
-- for historical seasons instead of only from the next refresh onward.
INSERT INTO season_entries (championship_id, driver_id, team_id)
SELECT championship_id, driver_id, team_id
FROM driver_classifications
WHERE championship_id IS NOT NULL AND driver_id IS NOT NULL
ON CONFLICT (championship_id, driver_id) DO NOTHING;
