/**
 * F1 nationality/country strings -> ISO 3166-1 alpha-2. The API gives us
 * free-text names, spelled inconsistently across endpoints — country names
 * ("United States"), demonyms ("American"), abbreviations ("UK"), and
 * outright typos ("Malasya" for Malaysia) all appear — so this is a
 * lookup table rather than a formula. This list was built by auditing
 * every distinct nationality/country string in the live driver and
 * circuit archives, not guessed from memory.
 */
const COUNTRY_TO_ISO2: Record<string, string> = {
  'Great Britain': 'GB',
  'United Kingdom': 'GB',
  UK: 'GB',
  England: 'GB',
  Scotland: 'GB',
  Netherlands: 'NL',
  Germany: 'DE',
  'West Germany': 'DE',
  'East Germany': 'DE',
  'East German': 'DE',
  Italy: 'IT',
  France: 'FR',
  Spain: 'ES',
  Monaco: 'MC',
  Austria: 'AT',
  Belgium: 'BE',
  Switzerland: 'CH',
  Finland: 'FI',
  Sweden: 'SE',
  Denmark: 'DK',
  Norway: 'NO',
  Poland: 'PL',
  Estonia: 'EE',
  'Czech Republic': 'CZ',
  Czechoslovakia: 'CZ',
  Ireland: 'IE',
  Hungary: 'HU',
  Portugal: 'PT',
  Russia: 'RU',
  'Soviet Union': 'RU',
  USSR: 'RU',
  Ukraine: 'UA',
  Canada: 'CA',
  'United States': 'US',
  USA: 'US',
  American: 'US',
  Mexico: 'MX',
  Brazil: 'BR',
  Argentina: 'AR',
  Uruguay: 'UY',
  Chile: 'CL',
  Colombia: 'CO',
  Venezuela: 'VE',
  Ecuador: 'EC',
  Peru: 'PE',
  Australia: 'AU',
  'New Zealand': 'NZ',
  Japan: 'JP',
  China: 'CN',
  'Hong Kong': 'HK',
  Thailand: 'TH',
  Malaysia: 'MY',
  Malasya: 'MY',
  Indonesia: 'ID',
  Singapore: 'SG',
  India: 'IN',
  'South Korea': 'KR',
  Korea: 'KR',
  Vietnam: 'VN',
  'South Africa': 'ZA',
  Morocco: 'MA',
  Egypt: 'EG',
  Tunisia: 'TN',
  Rhodesia: 'ZW',
  Zimbabwe: 'ZW',
  Nigeria: 'NG',
  Kenya: 'KE',
  Israel: 'IL',
  Turkey: 'TR',
  Lebanon: 'LB',
  'Saudi Arabia': 'SA',
  Qatar: 'QA',
  'United Arab Emirates': 'AE',
  Bahrain: 'BH',
  Bahrein: 'BH',
  Azerbaijan: 'AZ',
  Georgia: 'GE',
  Armenia: 'AM',
  Kazakhstan: 'KZ',
  Yugoslavia: 'RS',
  Serbia: 'RS',
  Croatia: 'HR',
  Slovakia: 'SK',
  Slovenia: 'SI',
  Romania: 'RO',
  Bulgaria: 'BG',
  Iceland: 'IS',
  Liechtenstein: 'LI',
  Luxembourg: 'LU',
  Malta: 'MT',
  Cyprus: 'CY',
  Andorra: 'AD',
  'San Marino': 'SM',
  'Puerto Rico': 'PR',
}

export function countryToISO2(name: string | null | undefined): string | null {
  if (!name) return null
  return COUNTRY_TO_ISO2[name.trim()] ?? null
}
